name: Cypress Tests

on:
  push:
    branches:
      - main 
      
  pull_request:
    branches:
      - main 
      - refinements

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'


  test_ubuntu:
    runs-on: ubuntu-latest
    needs:
      build_ubuntu
    steps:
      - name: Run Cypress tests on Ubuntu
        run: npx cypress run

      - name: Install dependencies
        run: npm ci

  test_windows:
    runs-on: windows-latest
    needs: 
      build_windows
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run